# This is the Cargo.toml for the entire workspace.
# It defines the member crates and can specify shared dependencies and settings.

[workspace]
# List all the crates that are part of this workspace.
members = [
    "ironstone",
    "ironstone-macros",
]
# Use the modern feature resolver for better dependency management.
resolver = "2"

# You can define shared package metadata for all member crates.
# This reduces boilerplate in the individual Cargo.toml files.
# [workspace.package]
# version = "0.1.0"
# edition = "2021"
# authors = ["Your Name <you@example.com>"]
# license = "MIT OR Apache-2.0"
# repository = "https://github.com/your-username/your-project"


# --- Your Local Crates ---
# This allows app-main to easily depend on app-macros.
# ironauth-macros = { path = "./ironauth-macros" }


# You can also define shared build profiles for all crates.
[profile.release]
lto = true          # Enable Link-Time Optimization for better performance.
codegen-units = 1   # Compile faster by parallelizing, but slower final binary. 1 is best for release.
strip = true        # Remove debug symbols from the final binary to reduce size.