services:
  # server:
  # env_file:
  #   - ./oxideauth/.env
  # build:
  #   context: ./oxideauth
  #   dockerfile: Dockerfile
  # volumes:
  #   - ./oxideauth:/app
  # ports:
  #   - 8080:8080

  # oxideauth-dashboard:
  #   env_file:
  #     - ./oxideauth-dashboard/.env
  #   build:
  #     context: ./oxideauth-dashboard
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./oxideauth-dashboard:/app
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - internal

  # flask-service:
  #   env_file:
  #     - ./flask-service/.env
  #   build:
  #     context: ./flask-service
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./flask-service:/app
  #   ports:
  #     - 8082:8082
  #   networks:
  #     - internal

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
